---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/gregory-katsaros-rft/environment-automation.git
    branch: master
    username: ((kv/rft/github-access-token))
    password: x-oauth-basic
jobs:
  - name: first-job
    plan: 
      - get: source-code
        trigger: true
      - set_pipeline: greg-automation-test
        file: source-code/pipeline.yaml
  - name: job
    public: true
    plan:
      - get: source-code
        trigger: true
        passed: [first-job]
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello, world!"]
            
  - name: any name
    public: true
    plan:
      - get: source-code
        trigger: true
        passed: [job]
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: debian }
          run:
            path: echo
            args: ["You shall not pass!"]
