---
resources:
- name: pipeline-source
    type: git
    icon: github-circle
    source:
      uri: https://github.com/gregory-katsaros-rft/environment-automation.git
      branch: develop
      username: ((kv/rft/github-access-token))
      password: x-oauth-basic

- name: environment-request
  type: git
  icon: github-circle
  source:
    uri: https://github.com/gregory-katsaros-rft/environment-request.git
    branch: demo
    username: ((kv/rft/github-access-token))
    password: x-oauth-basic
jobs:
  - name: first-job
    plan: 
      - get: pipeline-source
        trigger: true
      - set_pipeline: greg-automation-test
        file: source-code/pipeline.yaml
      - task: dummy-task
        file: pipeline-source/tasks/dummy-task.yml
  - name: job
    public: true
    plan:
      - get: environment-request
        trigger: true
        passed: [first-job]
      - task: dummy-task
        file: pipeline-source/tasks/dummy-task.yml
